# Generated by Django 2.0.2 on 2018-02-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obrazek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=120)),
                ('obrazek', models.FileField(upload_to='incidents')),
            ],
        ),
    ]
