# Generated by Django 2.0.2 on 2018-02-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Obrazek_obrazek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='File_Obrazek_obrazek2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='obrazek',
            name='obrazek',
            field=models.FileField(blank=True, null=True, upload_to='dbmedia.File_Obrazek_obrazek/bytes/filename/mimetype'),
        ),
        migrations.AlterField(
            model_name='obrazek',
            name='obrazek2',
            field=models.ImageField(blank=True, null=True, upload_to='dbmedia.File_Obrazek_obrazek2/bytes/filename/mimetype'),
        ),
    ]
